# Use Trusty beta environment: https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
sudo: false

language: node_js
node_js:
  - '4'
  - '6'
  - 'stable'

# Make Greenkeeper work with lockfiles:
# https://github.com/greenkeeperio/greenkeeper-lockfile/tree/f62f2f3e33cd1dd349c2898e0129c693cbc5804d#yarn
env:
  global:
    secure: LkUJeiAEKEYnVG97EC9EjTGbB6IpF+FkZNzuKuPcX5TiT7wXKLaOt/2bE5nN0plRcLqTpmXxgCmsqju0RVQbYXao65d2adPc6xvBMhB7M0TcGafTgtC3iw2cQN179IeRek8r44msVDXcPxAh144CoGsR0ogMppEsIn8CNdZWOYfGs691N68k24VxibJqoUpM1iDRGTs6xZ8SrF+hoHZAyS7bt7cp1htNvVm4d64U5TpbOL+L9zd3EtqaD6jXh7d609unCJurjCgl86WxQF1SS75xwasQeLV7292enB/stekBr8yqSfzMYIbjxRIg1upDsNSOxcqKMBEa3KNPkZcB/7LIjgNDCEanz876T06tjktaPibZWzAv91itf+DS8/bpilGHfLHtHdkOALVCxRiJ7tsERSprjN1jBd2h9bUQujz0yE+EOiBOPX3xnkOb7dfXxUo4z23vI7v/nODLCBpyV5LIG6t6o3tf2kNVAfQklOe68rlOpRIgDf25oBZ4AoYa5tvnQnYz0mJSLCOGLrWaj4Md62exOf1MaexMtFSEGMKvL1UPHnILiD0Kv7Lr/y6L8UCQ7cWWh22bMKvxxUFW1m950d4474cpIjxb944b3FrRKRvLC+vXpwFfc7LMp3Pw8WBTSVOGu30C1qHDke2OBMpD88tDwQGf4wDY6wD0yMA=

before_install:
# package-lock.json was introduced in npm@5
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
